name = "instance"
author = "amyavi"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e806c62cbcc837d95625472adf916bfeab49a321d2ea5f85a3ae075ea7d4e568"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
