name = "instance"
author = "amyavi"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c435a14d2140d709918780f99e40c03de6e5f68acdf03be22ff6deefdf7c3da9"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
