name = "instance"
author = "amyavi"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bc810a650b5d5d2a55025442bf4acb42fd9f4d0db20297a1e3f44341040719a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
